### ISSUE TITLE
Https Proxy

### ISSUE THREAD

**Issue by RaiserWeb** [mistakster/throttle-proxy#16]
Should this work on https traffic too? If not, would it be easy to set up?

**Comment by mistakster** [comment]
Hi. It doesn't work with HTTPS at the moment. I implemented a new version in a separate branch ([https://github.com/mistakster/throttle-proxy/tree/socks](socks)), but not released it yet. Could you try it and let me know if it works for you, please?

**Comment by RaiserWeb** [comment]
Hi Vladimir. Thanks for the message. I've tried this branch locally, but neither http or https load - browser just remained 'waiting for localhost' on http://localhost:3128 or https://localhost:3128. Tried different speed and port settings.

On 17/04/2016 08:49, Vladimir Kuznetsov wrote:

Hi. It doesn't work with HTTPS at the moment. I implemented a new version in a separate branch (https://github.com/mistakster/throttle-proxy/tree/socks<socks>), but not released it yet. Could you try it and let me know if it works for you, please?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/mistakster/throttle-proxy/issues/16#issuecomment-210971737>

--
@paulinsight<https://twitter.com/Paulinsight>

**Comment by mistakster** [comment]
Hi. 

Sorry, I forgot to notice, that it's SOCKS proxy now. Basically, HTTPS can be proxied only using SOCKS or SSH or other binary-safe transport layer.

Let me know if I can help you any further.

**Comment by mistakster** [comment]
I made some screenshots for your.

![SOCKS proxy configuration in OS X](https://cloud.githubusercontent.com/assets/531671/14604163/debd05d8-0593-11e6-8a0d-9a0ab00ade1a.png)

![SOCKS proxy configuration in Windows](https://cloud.githubusercontent.com/assets/531671/14604210/1cbcb766-0594-11e6-8e35-ace460bd8c40.png)

**Comment by RaiserWeb** [comment]
Hi, thanks for the screen shots. I'm actually implementing this on a VPS server, so guess I need to play around with SOCKS setting on the VPS. Will give it a go
