### ISSUE TITLE
Source port number

### ISSUE THREAD

**Issue by Diokuz** [mistakster/throttle-proxy#17]
Hi there)

I have a dev server, localhost:3000. How to setup throttle-proxy for that server?

For example, if I do `throttle-proxy --port 3001`, then it would listen for 3001 port. But how to set a source port, 3000?

Thanks in advance.

PS: I dont really want to install throttle-proxy globally. and use some system-level features.

**Comment by mistakster** [comment]
Hi.

`throttle-proxy` was designed to work on system level or application level, if a particular application supports proxy. It works as a gateway to the network.

As I understood you correctly, you'd like to have a gateway for your server, e.g. [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy). This feature is not supported.

If your dev server runs on Node.js, you may implement small a middleware based on [generic stream throttling module](https://www.npmjs.com/package/throttle).

Let me know if I can help you any further.

Cheers!
