### ISSUE TITLE
use a real proxy behind throttle-proxy

### ISSUE THREAD

**Issue by tareqhs** [mistakster/throttle-proxy#18]
Hi,

is there a way to configure `throttle-proxy` itself to use a proxy server?

thank you

**Comment by mistakster** [comment]
Hi Tareq!

I’ve just published version 0.8.0 with real proxy support you requested.

You can provide any valid IP address and port as URL string. throttle-proxy will use this server as intermediate proxy. Please, see an example below.

```
$ throttle-proxy --proxy http://35.162.160.108:8080
```

Let me know if I can help you any further.

**Comment by tareqhs** [comment]
Hi @mistakster ,

thanks for the quick response!

Please allow me explain further. I am using npm behind a corporate proxy but npm 5 bombards the network with open connections, sometimes hundreds of them, which causes the proxy to legitimately block npm installations. I am experimenting a solution method based on running a small "indirect proxy" between npm and the actual proxy. Is `throttle-proxy` suitable for this task?

thank you

**Comment by mistakster** [comment]
I see.

> Is throttle-proxy suitable for this task?

In short, no.  But you can set up relevant configuration options, so npm use your corporate proxy server natively.

https://docs.npmjs.com/misc/config#proxy
https://docs.npmjs.com/misc/config#https-proxy

Please, find an example below

```
npm config set http-proxy http://proxy.address:proxy.port
npm config set https-proxy http://proxy.address:proxy.port
```

> does it support https?

No, it doesn’t. The only one option to pass HTTPS connections is use SOCKS-proxy. I made an experimental version two years ago. Unfortunately, I didn’t finish the work.
