### ISSUE TITLE
Integrate with firefox?

### ISSUE THREAD

**Issue by Deathangel908** [mistakster/throttle-proxy#19]
Can I use throttle-proxy for firefox?
I setup the following proxy settings in firefox
![image](https://user-images.githubusercontent.com/1336703/38464528-d250459c-3b17-11e8-9333-f6428b54a2eb.png)

But pages don't load at all, even http. Proxy server seems to work
```: netstat -tulpn |grep 1080
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::1080                 :::*                    LISTEN      5120/node  
```

**Comment by mistakster** [comment]
@Deathangel908, you have to set only **SOCKS Host**.

Also, I recommend you to choose “Automatic proxy configuration URL” and set URL to `http://localhost:3128/`.

Let me know if I can help you any further.
