### ISSUE TITLE
--delay setting does not impact observed latency on FreeBSD 11.1 on 2.1.0

### ISSUE THREAD

**Issue by cpdohert** [mistakster/throttle-proxy#20]
I need to simulate real-world network conditions between a browser running on an Azure VM and an Azure web service.  I've inserted a FreeBSD 11.1 VM between them and run throttle-proxy with a --delay setting of 1000.

Running www.speedtest.net, ping, or www.azurespeed.com show no difference in observed latency regardless of what I set --delay to.  I have run throttle-proxy both as an unprivileged user and as root.

**Comment by mistakster** [comment]
@cpdohert, hi!

Yeah, I see the issue. Unfortunately, it’s not that easy to fix it. Let me explain what’s going on.

* CLI command `ping` doesn’t use proxy at all
* www.speedtest.net uses WebSockets to track a latency
* www.azurespeed.com uses `Connection: Keep-Alive` header and sends all requests in one connection

My tool applies delay only during initial connection. To simulate real-world network conditions you have to use smarter tools which intercept system network driver and deals with individual IP packets. It might I can apply delay on individual chunks of data. I need to make a series of experiments.

Sorry for inconvenience and thank you for the ideas how to test the tool.
