### ISSUE TITLE
wrong unit in the readme: incoming-speed is not in bps (bit per second). It's in Bps (byte per second)

### ISSUE THREAD

**Issue by linczy** [mistakster/throttle-proxy#22]
The documentation is not valid. the incoming-speed is using bytes per second and not bits per second. The symbol of bytes per second is Bps and not bps which seems to be bitspersecond.
https://en.wikipedia.org/wiki/Data-rate_units#Conversion_table
https://www.paessler.com/it-explained/bandwidth
The used _passthrough() function is based on byte and not bite.
https://www.npmjs.com/package/stream-parser#_passthroughn-cb

**Comment by mistakster** [comment]
Fixed. Thanks!
