### ISSUE TITLE
rate limit all traffic not per-connection

### ISSUE THREAD

**Issue by focusaurus** [mistakster/throttle-proxy#8]
This is probably a major code change, but would you consider making the limits for the entire proxy? Now AFAICT they are per-connection and if I just add more connections I get more "bandwidth" thus this is not useful if I want to emulate a slow network.

**Comment by mistakster** [comment]
Yes, you are right. It process connections independently. I need to think what I can do to apply limits for the entire proxy.

Thanks for you proposal.

**Comment by mistakster** [comment]
Hi @focusaurus

I’ve just published a quick patch. Server is counting incoming connections and reducing the base speed limit respectively. In fact, the limits are still not changing dynamically.

Please, try the new version (`0.5.0`) and let me know will it work for you.

Thanks.

**Comment by focusaurus** [comment]
Thanks for the very quick patch! I tried it and it indeed does work much better, at least for my case. I would think there may be a more correct place to limit the overall TCP server, but this helps for now.

**Comment by mistakster** [comment]
Cool.

Actually, I'm using [throttle](https://www.npmjs.com/package/throttle) module under the hood. I do believe that it's possible to implement more accurate algorithm in my own custom implementation.
