### ISSUE TITLE
How about adding the Server Response Time to the parameters?

### ISSUE THREAD

**Issue by MoritzGiessmann** [mistakster/throttle-proxy#9]
Like the title says, it would be nice to simulate a server response time > 0ms. A simple setTimeout would do that IMO. What do you think about that?

**Comment by mistakster** [comment]
Hi Moritz! Thanks for your request.

I’ve just published v0.6.0 with support `--delay` option. Also, you may set delay using short alias `-d`.

**Comment by MoritzGiessmann** [comment]
So cool! Thanks :+1:
